const PATTERN_NAMES = {
  wawawddew: "Gravitational Purification (Gravity Changer)",
  wdwdwaaqw: "Alter Gravity (Gravity Changer)",
  aawawwawwa: "Gulliver's Purification (Pehkui)",
  ddwdwwdwwd: "Alter Scale (Pehkui)",
  qaq: "Mind's Reflection",
  wa: "Alidade's Purification",
  awq: "Stadiometer's Purification",
  wq: "Pace Purification",
  wqaawdd: "Archer's Distillation",
  weddwaa: "Architect's Distillation",
  weaqa: "Scout's Distillation",
  eaqwqae: "Waystone Reflection",
  eaqwqaewede: "Lodestone Reflection",
  eaqwqaewdd: "Lesser Fold Reflection",
  aqwqawaaqa: "Greater Fold Reflection",
  aadaa: "Gemini Decomposition",
  aadaadaa: "Gemini's Gambit",
  qwaeawqaeaqa: "Flock's Reflection",
  aawdd: "Jester's Gambit",
  ddad: "Fisherman's Gambit",
  qaawdde: "Swindler's Gambit",
  waaw: "Additive Distillation",
  wddw: "Subtractive Distillation",
  waqaw: "Multiplicative Distillation",
  wdedw: "Division Distillation",
  wqaqw: "Length Purification",
  wedew: "Power Distillation",
  ewq: "Floor Purification",
  qwe: "Ceiling Purification",
  eqqqqq: "Vector Exaltation",
  qeeeee: "Vector Disintegration",
  qqqqqaww: "Axial Purification",
  wdw: "Conjunction Distillation",
  waw: "Disjunction Distillation",
  dwa: "Exclusion Distillation",
  e: "Maximus Distillation",
  q: "Minimus Distillation",
  ee: "Maximus Distillation II",
  qq: "Minimus Distillation II",
  ad: "Equality Distillation",
  da: "Inequality Distillation",
  dw: "Negation Purification",
  aw: "Augur's Purification",
  eqqq: "Entropy Reflection",
  qqqqqaa: "Sine Purification",
  qqqqqad: "Cosine Purification",
  wqqqqqadq: "Tangent Purification",
  ddeeeee: "Inverse Sine Purification",
  adeeeee: "Inverse Cosine Purification",
  eadeeeeew: "Inverse Tangent Purification",
  eqaqe: "Logarithmic Distillation",
  addwaad: "Modulus Distillation",
  wdweaqa: "Intersection Distillation",
  waweaqa: "Unifying Distillation",
  dwaeaqa: "Exclusionary Distillation",
  dweaqa: "Inversion Purification",
  aweaqa: "Uniqueness Purification",
  de: "Reveal",
  aawaawaa: "Explosion",
  ddwddwdd: "Fireball",
  awqqqwaqw: "Impulse",
  awqqqwaq: "Blink",
  qaqqqqq: "Break Block",
  eeeeede: "Place Block",
  awddwqawqwawq: "Internalize Pigment",
  aqawqadaq: "Create Water",
  dedwedade: "Destroy Water",
  aaqawawa: "Ignite Block",
  ddedwdwd: "Extinguish Area",
  qqa: "Conjure Block",
  qqd: "Conjure Light",
  wqaqwawqaqw: "Overgrow",
  qqqqqwaeaeaeaeaea: "Recharge Item",
  qdqawwaww: "Erase Item",
  wqaqwd: "Edify Sapling",
  adaa: "Make Note",
  waqqqqq: "Craft Cypher",
  wwaqqqqqeaqeaeqqqeaeq: "Craft Trinket",
  wwaqqqqqeawqwqwqwqwqwwqqeadaeqqeqqeadaeqq: "Craft Artifact",
  qqqqqaqwawaw: "White Sun's Nadir",
  qqqqqawwawawd: "Blue Sun's Nadir",
  qqqqqaewawawe: "Black Sun's Nadir",
  qqqqqadwawaww: "Red Sun's Nadir",
  qqqqqadwawaw: "Green Sun's Nadir",
  waeawae: "Summon Sentinel",
  qdwdqdw: "Banish Sentinel",
  waeawaede: "Locate Sentinel",
  waeawaedwa: "Wayfind Sentinel",
  qqqwqqqqqaq: "Akasha's Distillation",
  eeeweeeeede: "Akasha's Gambit",
  qqq: "Introspection",
  eee: "Retrospection",
  qqqaw: "Consideration",
  deaqq: "Hermes' Gambit",
  aqdee: "Charon's Gambit",
  aqqqqq: "Scribe's Reflection",
  deeeee: "Scribe's Gambit",
  aqqqqqe: "Auditor's Reflection",
  deeeeeq: "Assessor's Reflection",
  wawqwqwqwqwqwew: "Auditor's Purification",
  qeewdweddw: "Muninn's Reflection",
  eqqwawqaaw: "Huginn's Gambit",
  d: "Nullary Reflection",
  qqqqqea: "Vector Reflection +X",
  qqqqqew: "Vector Reflection +Y",
  qqqqqed: "Vector Reflection +Z",
  eeeeeqa: "Vector Reflection -X",
  eeeeeqw: "Vector Reflection -Y",
  eeeeeqd: "Vector Reflection -Z",
  qdwdq: "Arc's Reflection",
  eawae: "Circle's Reflection",
  aaq: "Euler's Reflection",
  qqqqqdaqa: "Entity Purification",
  qqqqqdaqaawa: "Entity Purification - Animal",
  qqqqqdaqaawq: "Entity Purification - Monster",
  qqqqqdaqaaww: "Entity Purification - Item",
  qqqqqdaqaawe: "Entity Purification - Player",
  qqqqqdaqaawd: "Entity Purification - Living",
  qqqqqwded: "Zone Distillation - Any",
  qqqqqwdeddwa: "Zone Distillation - Animal",
  eeeeewaqaawa: "Zone Distillation - Non-Animal",
  qqqqqwdeddwq: "Zone Distillation - Monster",
  eeeeewaqaawq: "Zone Distillation - Non-Monster",
  qqqqqwdeddww: "Zone Distillation - Item",
  eeeeewaqaaww: "Zone Distillation - Non-Item",
  qqqqqwdeddwe: "Zone Distillation - Player",
  eeeeewaqaawe: "Zone Distillation - Non-Player",
  qqqqqwdeddwd: "Zone Distillation - Living",
  eeeeewaqaawd: "Zone Distillation - Non-Living",
  edqde: "Integration Distillation",
  qaeaq: "Combination Distillation",
  deeed: "Selection Distillation",
  dadad: "Thoth's Gambit",
  aqaeaq: "Abacus Purification",
  adeeed: "Single's Purification",
  qqaeaae: "Vacant Reflection",
  qqqaede: "Retrograde Purification",
  ewdqdwe: "Flock's Gambit",
  qwaeawq: "Flock's Disintegration",
  dedqde: "Locator's Distillation",
  edqdewaqa: "Excisor's Distillation",
  qaeaqwded: "Selection Exaltation",
  wqaeaqw: "Surgeon's Exaltation",
  ddewedd: "Speaker's Distillation",
  aaqwqaa: "Speaker's Decomposition",
  ddwaa: "Timekeeper's Reflection (Hexal)",
  wqqqwqqadad: "Smelt (Hexal)",
  weeeweedada: "Freeze (Hexal)",
  wqwawqwqwqwqwqw: "Falling Block (Hexal)",
  aqaeqeeeee: "Summon Projectile Wisp (Hexal)",
  aqaweewaqawee: "Summon Cyclic Wisp (Hexal)",
  aqaweewaqaweedw: "Reservoir Reflection (Hexal)",
  eedqa: "Thanatos' Reflection (Hexal)",
  aweewaqaweewaawww: "Manager's Purification (Hexal)",
  qqwdedwqqdaqaaww: "Entity Purification - Wisp (Hexal)",
  qqwdedwqqwdeddww: "Zone Distillation - Wisp (Hexal)",
  eewaqaweewaqaaww: "Zone Distillation - Non-Wisp (Hexal)",
  aqawded: "Delay Wisp (Hexal)",
  aqqqqqwdeddw: "Listen (Hexal)",
  eaqaaeqqqqqaweaqaaw: "Link Entity (Hexal)",
  qdeddqeeeeedwqdeddw: "Unlink (Hexal)",
  eqqqqqaww: "Phonebook Purification (Hexal)",
  aeqqqqqawwd: "Recognition Purification (Hexal)",
  qeeeeedww: "Popularity Reflection (Hexal)",
  qqqqqwdeddw: "Send Iota (Hexal)",
  weeeeew: "Recitation Reflection (Hexal)",
  aweeeeewaa: "Postmaster's Reflection (Hexal)",
  a: "Bookkeeper's Gambit (v)",
  "": "Bookkeeper's Gambit (-)",
  aqawdwaqawd: "Diver's Purification (Hexal)",
  aqwawqa: "Nurse's Purification (Hexal)",
  qedqde: "Lamplighter's Purification (Hexal)",
  eweeewedqdeddw: "Mnemosyne's Gambit (Hexal)",
  qwqqqwqaeaqaaw: "Elysium's Gambit (Hexal)",
  qwqqqwqaww: "Lethe's Gambit (Hexal)",
  awqwawqaw: "Pathfinder's Gambit (Hexal)",
  ewdwewdew: "Pathfinder's Reflection (Hexal)",
  eqwawqwaqww: "Wander (Hexal)",
  eweeewedww: "Brigh's Gambit (Hexal)",
  qqqqq: "Vector Reflection Zero",
  qwdedwq: "Open Transmit (Hexal)",
  ewaqawe: "Close Transmit (Hexal)",
  qaqqaea: "Sorter's Purification (Hexal)",
  qawde: "Physician's Purification (Hexal)",
  awd: "Numerologist's Purification",
  wqqqqw: "Squire's Purification (Hexal)",
  aeqqqqea: "Boxer's Purification (Hexal)",
  wawdedwaw: "Factorial Purification (Hexal)",
  aea: "Running Sum Purification (Hexal)",
  qaawaaq: "Running Product Purification (Hexal)",
  eeeeedeeeee: "Place Block II (Hexal)",
  eqqqqa: "Particles (Hexal)",
  dedwqqwdedwqqaw: "Identity Reflection (Hexal)",
  dwqqwdedwqqwddwww: "Allegiance Distillation (Hexal)",
  aeawqqqae: "Haste (Hexal)",
  eeewdqdee: "Speedometer's Reflection (Hexal)",
  daqweewqaeaqweewqaqwwww: "Familiar's Reflection (Hexal)",
  eqqqqqawqeeeeedww: "Link Others (Hexal)",
  aweeeeewa: "Unclogging Gambit (Hexal)",
  qaqeede: "Gate's Opening (Hexal)",
  qqqwwqqqwqqawdedw: "Gate's Closing (Hexal)",
  dd: "Compass Purification II",
  aa: "Compass Purification",
  aaeaa: "Rotation Gambit",
  ddqdd: "Rotation Gambit II",
  aaedd: "Prospector's Gambit",
  ddqaa: "Undertaker's Gambit",
  aadadaaw: "Dioscuri Gambit",
  aada: "Fisherman's Gambit II",
  awdd: "Augur's Exaltation",
  wdwewewewewew: "Chronicler's Gambit",
  wawqwqwqwqwqw: "Chronicler's Purification",
  wdwewewewewewqw: "Assessor's Purification",
  awawaawq: "Anchorite's Flight",
  dwdwdewq: "Wayfarer's Flight",
  qwaqde: "Iris' Gambit",
  awdwa: "Blank Reflection (MoreIotas)",
  awdwaaww: "Spacing Reflection (MoreIotas)",
  qa: "Comma Reflection (MoreIotas)",
  waawaw: "Breaking Reflection (MoreIotas)",
  awqwawqe: "Reader's Purification (MoreIotas)",
  waqa: "Whisper Reflection (MoreIotas)",
  wded: "Listener's Reflection (MoreIotas)",
  qwaqa: "Sifter's Gambit (MoreIotas)",
  ewded: "Sifter's Reflection (MoreIotas)",
  wawqwawaw: "Scrivener's Purification (MoreIotas)",
  wdwewdwdw: "Patternmaster's Purification (MoreIotas)",
  waawaqwawqq: "Concatenation Distillation (MoreIotas)",
  aqwaqa: "Separation Distillation (MoreIotas)",
  aqwaq: "Input Purification (MoreIotas)",
  waqwwaqa: "Discoverer's Distillation (MoreIotas)",
  aqwwaqwaad: "Winnowing Distillation (MoreIotas)",
  waqaeaq: "Length Distillation: Str (MoreIotas)",
  awwaeawwaadwa: "Transformation Purification (MoreIotas)",
  dwwdqdwwddawd: "Restoration Purification (MoreIotas)",
  awwaeawwaqw: "Identity Purification (MoreIotas)",
  awwaeawwa: "Zero Distillation (MoreIotas)",
  awwaeawwawawddw: "Rotation Distillation (MoreIotas)",
  waawawaeawwaea: "Addition Distillation: Matrix (MoreIotas)",
  waqawawwaeaww: "Multiplication Distillation: Matrix (MoreIotas)",
  wwaeawwaede: "Transpose Purification (MoreIotas)",
  wwdqdwwdqaq: "Inverse Purification (MoreIotas)",
  aeawwaeawaw: "Determinant Purification (MoreIotas)",
  awwaeawwawawdedwa: "Tower Distillation (MoreIotas)",
  dwwdqdwwdwdwaqawd: "Sprawling Distillation (MoreIotas)",
  awdedwawawwaeawwa: "Toppling Gambit (MoreIotas)",
  dwaqawdwdwwdqdwwd: "Mitosis Gambit (MoreIotas)",
  wqwawqqawddwqwede: "Memorize Pigment (Hexbound)",
  wqwawqqawddwqeqaq: "Recall Pigment (Hexbound)",
  wqwawqqawddwqwdd: "Forget Pigment (Hexbound)",
  eweeewe: "Hex Shield (Hexbound)",
  eqdweeqdw: "Unstable Hex Shield (Hexbound)",
  deeee: "Revolving Distillation (Hexbound)",
  aqqqqa: "Painter's Distillation (Hexbound)",
  wqqqq: "Starting Distillation (Hexbound)",
  weeee: "Ending Distillation (Hexbound)",
  eqqqq: "Fragment's Purification (Hexbound)",
  qeeee: "Winding Purification (Hexbound)",
  qaawedee: "Automaton's Reflection (Hexbound)",
  eddeawaw: "Command: Pick Up Item (Hexbound)",
  qaaqdwdw: "Command: Drop Item (Hexbound)",
  qaaqwdaqqqa: "Command: Move To Position (Hexbound)",
  qaaqqedwed: "Command: Harvest (Hexbound)",
  qaaqdee: "Command: Use On Block (Hexbound)",
  wqaawddewdwewewewewew: "Artificer's Gambit (Hexbound)",
  qaaq: "Send Instructions (Hexbound)",
  qqaaqqqqwq: "Broadcast Instructions (Hexbound)",
  adeq: "Duelist's Purification (Hexbound)",
  qeda: "Shieldbearer's Purification (Hexbound)",
  aqwed: "Hoarder's Distillation (Hexbound)",
  dewqa: "Collector's Distillation (Hexbound)",
  dedqaq: "Treasurer's Purification (Hexbound)",
  dedqaa: "Logistician's Purification (Hexbound)",
  wqwqwwqwqwqwwaeqaqdwdqaqe: "Create Spider Construct (Hexbound)",
  qqqqqdaqaawedde: "Entity Purification: Construct (Hexbound)",
  qqqqqwdeddwedde: "Zone Distillation: Construct (Hexbound)",
  eeeeewaqaawedde: "Zone Distillation: Non-Construct (Hexbound)",
};